name: implications
services:
  auto_implications:
    container_name: autoimplications
    build:
      context: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./autoimplications/:/app/autoimplications/
      - ./data/:/app/data/
      - ./run_tasks.sh:/app/run_tasks.sh
      - ./config.yaml:/app/config.yaml
      - ./bigquery_keys.json:/app/bigquery_keys.json
    command: /bin/sh -c "/app/run_tasks.sh"
